<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="LocalHelper.fs" />
    <Content Include="problem0\input_0.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="problem0\sample_input_0.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="problem0\Problem0.fs" />
    <Content Include="Problem1\input_1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Problem1\sample_input_1.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="problem1\sample_input_2.txt" />
    <Compile Include="Problem1\Problem1.fs" />
    <Folder Include="Problem2\" />
    <Content Include="problem2\input_2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="problem2\sample_input_2.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="problem2\Problem2.fs" />
    <Folder Include="Problem3\" />
    <Content Include="problem3\input_3.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="problem3\sample_input_3.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="problem3\Problem3.fs" />
    <Folder Include="Problem4\" />
    <Content Include="problem4\input_4.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="problem4\sample_input_4.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Compile Include="problem4\Problem4.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Problem0\" />
  </ItemGroup>

</Project>
